######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 26 12:38:17 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += app.h medium.h pathtracer.h threadpool.h world.h
SOURCES += app.cpp main.cpp pathtracer.cpp threadpool.cpp world.cpp
